# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20151230_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_section',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.RecipeSection'),
            preserve_default=False,
        ),
    ]
