# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20151230_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('Volume', (('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('fl oz', 'Fluid ounce'), ('c', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('ml', 'Milliliter'), ('l', 'Liter'), ('dl', 'Deciliter'))), ('Mass', (('lb', 'Pound'), ('oz', 'Ounce'), ('mg', 'Milligram'), 'g', 'Gram', ('kg', 'Kilogram'))), ('Length', (('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('in', 'Inch'), ('yd', 'Yard'))), ('Other', (('clove', 'Clove'), ('stalk', 'Stalk'), ('package', 'Package'), ('bag', 'Bag'), ('stick', 'Stick'), ('dash', 'Dash'), ('peck', 'Peck'), ('bushel', 'Bushel'), ('can', 'Can'), ('stone', 'Stone'), ('vine', 'Vine'), ('envelope', 'Envelope'), ('box', 'Box'), ('pinch', 'Pinch'), ('cube', 'Cube'), ('square', 'Square'), ('part', 'Part'), ('bunch', 'Bunch'), ('jar', 'Jar'), ('wedge', 'Wedge'), ('slice', 'Slice'), ('container', 'Container'), ('link', 'Link'), ('unit', 'Unit'), ('slice', 'Slice'))), ('none', 'None')], default='none', max_length=200),
            preserve_default=False,
        ),
    ]
