# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20151230_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ingredient', verbose_name='Item Name (existing)'),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item Name (custom)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='prep_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='prep_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipelist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipelistmember',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
