# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20151230_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelistmember',
            name='recipe_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.RecipeList'),
        ),
    ]
