# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20151231_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=8)),
                ('v_code', models.CharField(max_length=65)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pantryitem',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='pantryitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pantrylocation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe_section',
        ),
        migrations.RemoveField(
            model_name='recipelist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='recipelistmember',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipelistmember',
            name='recipe_list',
        ),
        migrations.RemoveField(
            model_name='recipesection',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='PantryItem',
        ),
        migrations.DeleteModel(
            name='PantryLocation',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.DeleteModel(
            name='RecipeList',
        ),
        migrations.DeleteModel(
            name='RecipeListMember',
        ),
        migrations.DeleteModel(
            name='RecipeSection',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
