# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160528_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='api_id',
            new_name='key_id',
        ),
    ]
