# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160528_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='main', max_length=100),
            preserve_default=False,
        ),
    ]
