UNITS = (
    ('Volume', (
        ('tsp', 'Teaspoon'),
        ('tbsp', 'Tablespoon'),
        ('fl oz', 'Fluid ounce'),
        ('c', 'Cup'),
        ('pt', 'Pint'),
        ('qt', 'Quart'),
        ('gal', 'Gallon'),
        ('ml', 'Milliliter'),
        ('l', 'Liter'),
        ('dl', 'Deciliter'),
    )),
    ('Mass', (
        ('lb', 'Pound'),
        ('oz', 'Ounce'),
        ('mg', 'Milligram'),
        ('g', 'Gram'),
        ('kg', 'Kilogram'),
    )),
    ('Length', (
        ('mm', 'Millimeter'),
        ('cm', 'Centimeter'),
        ('m',  'Meter'),
        ('in', 'Inch'),
        ('yd', 'Yard'),
    )),
    ('Other', (
        ('clove', 'Clove'),
        ('stalk', 'Stalk'),
        ('package', 'Package'),
        ('bag', 'Bag'),
        ('stick', 'Stick'),
        ('dash', 'Dash'),
        ('peck', 'Peck'),
        ('bushel', 'Bushel'),
        ('can', 'Can'),
        ('stone', 'Stone'),
        ('vine', 'Vine'),
        ('envelope', 'Envelope'),
        ('box', 'Box'),
        ('pinch', 'Pinch'),
        ('cube', 'Cube'),
        ('square', 'Square'),
        ('part', 'Part'),
        ('bunch', 'Bunch'),
        ('jar', 'Jar'),
        ('wedge', 'Wedge'),
        ('slice', 'Slice'),
        ('container', 'Container'),
        ('link', 'Link'),
        ('unit', 'Unit'),
        ('slice', 'Slice')
    )),
    ('none', 'None')
)
